name: deploy package
on:
  release:
    types: [ published ]
jobs:
  tox-ci:
    uses: QualiSystems/.github/.github/workflows/package-tox-py-39.yml@master
  pypi-deploy:
    needs: tox-ci
    uses: QualiSystems/.github/.github/workflows/package-deploy-pypi.yml@master
    secrets: inherit
